language: ruby
rvm:
- 2.4.0
branches:
  only:
  - master
addons:
  ssh_known_hosts: 172.104.113.239

before_install:
- openssl aes-256-cbc -K $encrypted_c965527be372_key -iv $encrypted_c965527be372_iv -in jesor_rsa.enc -out jesor_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 jesor_rsa
- ssh-add jesor_rsa

script: bundle exec
script: gem install jekyll
script: jekyll build --config _config.yml
script: ls

