url: "https://dev.jesor.me"
title: "大破进击"
description: "廃人日志。Cross the sea, we're still you and me."

lang: zh
timezone: Asia/Shanghai

site:
  url: https://dev.jesor.me

author:
  name: Jesse
  email: jessechan42@gmail.com
  twitter: Jesoooor
  telegram: Jesoooor
  zhihu: jesor
  instagram: jesoooor

toc:
  # selectors: 'h1,h2,h3'

pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: '/page/:num/'
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 4
    after: 5

excerpt_separator: <!--more-->
permalink: /:year/:title/

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json
  - /node_modules
  - /vendor
  - .gitignore
  - .travis.yml
  - jesor_rsa.enc
  - jesor_rsa
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - "*.sublime-project"
  - "*.sublime-workspace"

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jemoji

defaults:
  - scope:
      path: "_posts/blog"
    values:
      layout: post
      category: blog
      
  - scope:
      path: "_posts/microblog"
    values:
      layout: post
      category: blog


  - scope:
      path: "_pages"
    values:
      layout: page
