url: "https://dev.jesor.me"
title: "大破进击"
description: "廃人日志。Cross the sea, we're still you and me."
nav_lists:
  - titles:
      zh: 关于本站
    url: /about.html

lang: zh
timezone: Asia/Shanghai

site:
  url: https://dev.jesor.me

author:
  name: Jesse
  email: jessechan42@gmail.com
  twitter: Jesoooor
  telegram: Jesoooor
  zhihu: jesor
  instagram: jesoooor

toc:
  # selectors: 'h1,h2,h3'

paginate: 5
paginate_path: /page:num/

excerpt_separator: <!--more-->
permalink: /:year/:title/

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json
  - /node_modules
  - /vendor

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post


  - scope:
      path: "_pages"
    values:
      layout: page
