url: "https://jesor.me"
title: "大破进击"
description: "廃人日志。"
logo: /assets/images/logo/android-chrome-512x512.png
lang: zh
timezone: Asia/Shanghai

twitter:
  username: Jesoooor

site:
  url: https://jesor.me

author:
  name: Jesse
  email: jessechan42@gmail.com
  twitter: Jesoooor
  telegram: Jesoooor
  zhihu: jesor
  instagram: jesoooor
  channel: forwardlikehell

toc:
  # selectors: 'h1,h2,h3'

ga_tracking_id: UA-114350775-1
# mermaid: true
# chart: true
pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: '/page/:num/'
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 3
    after: 3

excerpt_separator: <!--more-->
permalink: /:year/:title/

markdown: kramdown
highlighter: rouge

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json
  - /node_modules
  - /vendor
  - .gitignore
  - .travis.yml
  - jesor_rsa.enc
  - jesor_rsa
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - "*.sublime-project"
  - "*.sublime-workspace"

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jemoji
  - jekyll-seo-tag

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      categories: blog
      image: /assets/images/logo/android-chrome-512x512.png

  - scope:
      path: "_pages"
    values:
      image: /assets/images/logo/android-chrome-512x512.png

